export const ScreenSizes = {
  S: 320,
  XS: 375,
  M: 485,
  M_2: 600,
  M_1: 700,
  XM: 768,
  XM_1: 900,
  L: 1024,
  L_3: 1100,
  L_2: 1200,
  L_1: 1300,
  XL: 1440,
  XL_2: 1565,
  XL_1: 1775,
  XXL: 2560,
}

export const query = {
  S: `(max-width: ${ScreenSizes.S}px)`,
  XS: `(max-width: ${ScreenSizes.XS}px)`,
  M: `(max-width: ${ScreenSizes.M}px)`,
  M_2: `(max-width: ${ScreenSizes.M_2}px)`,
  M_1: `(max-width: ${ScreenSizes.M_1}px)`,
  XM: `(max-width: ${ScreenSizes.XM}px)`,
  XM_1: `(max-width: ${ScreenSizes.XM_1}px)`,
  L: `(max-width: ${ScreenSizes.L}px)`,
  L_3: `(max-width: ${ScreenSizes.L_3}px)`,
  L_2: `(max-width: ${ScreenSizes.L_2}px)`,
  L_1: `(max-width: ${ScreenSizes.L_1}px)`,
  XL: `(max-width: ${ScreenSizes.XL}px)`,
  XL_2: `(max-width: ${ScreenSizes.XL_2}px)`,
  XL_1: `(max-width: ${ScreenSizes.XL_1}px)`,
  XXL: `(max-width: ${ScreenSizes.XXL}px)`,
};
